#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#Added Ant
export ANT_HOME=$HOME/bin/ant
export PATH=$PATH:$ANT_HOME/bin

#Added local bin
export PATH=$PATH:$HOME/bin

export EDITOR='vim'
export VISUAL='sublime'

